### ISSUE TITLE
Suggest: Support the warpback for Recall Potion

### ISSUE THREAD

**Issue by sgkoishi** [Smelltastic/TShock_MirrorWarpback#1]
In fact, there are many ways to teleport in game.
Recall potion ( 2350 ) can teleport back to home, and it should be add in MirrorWarpback.cs ( Line 209 ) 

Also, Wormhole potion ( 2997 ) and Teleportation potioncan ( 2351 ) teleport people to other places. Would it be add to the support list?

**Comment by Smelltastic** [comment]
This can already be done by modifying the config file mirrorwarpback.json to meet your needs.
